-- Schema SQL para Radar Financiero
-- Configura todas las tablas del modelo de datos con acceso público

-- 1. Tabla de Registros (Usuarios)
CREATE TABLE IF NOT EXISTS public.registros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Perfiles
CREATE TABLE IF NOT EXISTS public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id BIGINT REFERENCES public.registros(id) ON DELETE CASCADE,
    avatar_url TEXT,
    bio TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Bancos
CREATE TABLE IF NOT EXISTS public.banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Productos Financieros
CREATE TABLE IF NOT EXISTS public.financial_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT REFERENCES public.banks(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL CHECK (type IN ('dpf', 'caja_ahorro', 'credito')),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tasas de Interés
CREATE TABLE IF NOT EXISTS public.interest_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.financial_products(id) ON DELETE CASCADE,
    rate_type VARCHAR(50) NOT NULL CHECK (rate_type IN ('active', 'passive')),
    rate NUMERIC(5,2) NOT NULL, -- Ej: 5.50 para 5.5%
    term_days INTEGER,          -- Plazo en días (para DPF)
    min_amount NUMERIC(12,2),   -- Monto mínimo de apertura
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Indicadores Económicos
CREATE TABLE IF NOT EXISTS public.economic_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    value NUMERIC(10,4) NOT NULL,
    unit VARCHAR(50) NOT NULL,  -- Ej: '%', 'Bs', 'UFV'
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Modelos de Riesgo
CREATE TABLE IF NOT EXISTS public.risk_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    formula_params JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Watchlists (Favoritos)
CREATE TABLE IF NOT EXISTS public.watchlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id BIGINT REFERENCES public.registros(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.financial_products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(registro_id, product_id)
);

-- 9. Notificaciones / Alertas
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) DEFAULT 'info', -- 'info', 'warning', 'success', 'rate_change'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Preferencias de Usuario
CREATE TABLE IF NOT EXISTS public.user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id BIGINT REFERENCES public.registros(id) ON DELETE CASCADE UNIQUE,
    theme VARCHAR(50) DEFAULT 'dark',
    receive_emails BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Logs de Auditoría
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- HABILITAR ROW LEVEL SECURITY (RLS) en todas las tablas para permitir acceso controlado por políticas
ALTER TABLE public.registros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interest_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.economic_indicators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- CREAR POLÍTICAS PÚBLICAS DE RESPALDO (Por si RLS se activa en el dashboard de Supabase)
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
          AND table_type = 'BASE TABLE'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Permitir select público" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permitir select público" ON public.%I FOR SELECT TO public USING (true)', t);

        EXECUTE format('DROP POLICY IF EXISTS "Permitir insert público" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permitir insert público" ON public.%I FOR INSERT TO public WITH CHECK (true)', t);

        EXECUTE format('DROP POLICY IF EXISTS "Permitir update público" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permitir update público" ON public.%I FOR UPDATE TO public USING (true) WITH CHECK (true)', t);

        EXECUTE format('DROP POLICY IF EXISTS "Permitir delete público" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permitir delete público" ON public.%I FOR DELETE TO public USING (true)', t);
    END LOOP;
END $$;
